---
- name: Clone superset repository locally.
  become: true
  become_user: "{{ superset_local_build_user }}"
  git:
    accept_hostkey: "yes"
    repo: "{{ superset_git_url }}"
    version: "{{ superset_version }}"
    dest: "{{ superset_local_build_directory }}"
    force: yes
  delegate_to: "127.0.0.1"
  when: superset_install_from_git|bool

- name: Install javascript dependencies
  become: true
  become_user: "{{ superset_local_build_user }}"
  npm:
    path: "{{ superset_local_build_directory }}/superset/static/assets"
    executable: "{{ superset_local_build_npm_dir }}/npm"
  delegate_to: "127.0.0.1"
  environment:
    PATH: "{{ superset_local_build_npm_dir }}:{{ lookup('env', 'PATH') }}"
  when: superset_install_from_git|bool

- name: Compile javascript
  become: true
  become_user: "{{ superset_local_build_user }}"
  command: "{{ superset_local_build_npm_dir }}/npm ci && {{ superset_local_build_npm_dir }}/npm run prod"
  args:
    chdir: "{{ superset_local_build_directory }}/superset-frontend"
  environment:
    PATH: "{{ superset_local_build_npm_dir }}:{{ lookup('env', 'PATH') }}"
  delegate_to: "127.0.0.1"
  when: superset_install_from_git|bool
