---
- name: Copy superset branding images.
  copy:
    src: "files/{{ item }}"
    dest: "{{ superset_base_path }}/static/assets/images/{{ item }}"
  with_items:
    - "{{ superset_favicon_path }}"
    - "{{ superset_logo_path }}"
    - "{{ superset_2x_logo_path }}"
  when: superset_white_label_use_filepaths|bool

- name: Ensure Superset is restarted
  service: name=superset state=restarted
  when: superset_force_restart|bool
